import type { Metadata } from "next";
import { Lato, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { UserProvider } from "@/context/userContext";

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-lato',
});

const nunito = Nunito({
  subsets: ['latin'],    
  weight: ['400', '700'],    
  variable: '--font-nunito', 
});

export const metadata: Metadata = {
  title: "RafficToe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className}`}
      >
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
